<?php

  /**
 * Register Custom Navigation Walker
 */
  function register_navwalker(){
	  require_once get_template_directory() . '/class-wp-bootstrap-navwalker.php';
  }

  add_action( 'after_setup_theme', 'register_navwalker' );

  if ( ! file_exists( get_template_directory() . '/class-wp-bootstrap-navwalker.php' ) ) {
    // File does not exist... return an error.
    return new WP_Error( 'class-wp-bootstrap-navwalker-missing', __( 'It appears the class-wp-bootstrap-navwalker.php file may be missing.', 'wp-bootstrap-navwalker' ) );
} else {
    // File exists... require it.
    require_once get_template_directory() . '/class-wp-bootstrap-navwalker.php';
}


   // Theme Support
  function wpb_theme_setup(){

    // Post Thumbnails Activation
    add_theme_support('post-thumbnails');

    // Nav Menus
    register_nav_menus(array(
      'primary' => __('Primary Menu', 'Mughal Blogs')
    ));

    
  }
   
   // add action for theme support 
   add_action('after_setup_theme','wpb_theme_setup');


  // Function To load CSS Stylesheets
  function themebs_enqueue_styles() {

    // Integrating Bootstrap In Theme 
    wp_enqueue_style( 'bootstrap', get_template_directory_uri() . '/css/bootstrap.min.css' );

    // Styling For Navbar
    wp_enqueue_style( 'navbar', get_template_directory_uri() . '/css/navbar.css' );

    // Styling For Showcase
    wp_enqueue_style( 'showcase', get_template_directory_uri() . '/css/section-showcase.css');

    // Styling For Shots Section
    wp_enqueue_style( 'shots', get_template_directory_uri() . '/css/section-shots.css' );

    // Testimonial Section Styling
    wp_enqueue_style( 'testimonial', get_template_directory_uri() . '/css/section-testimonial.css' );

    // Recent Section Styling
    wp_enqueue_style( 'posts', get_template_directory_uri() . '/css/section-posts.css' );

    // Template Archive Template
    wp_enqueue_style( 'archive-template', get_template_directory_uri() . '/css/template-archive.css' );

    // Template Archive Shots
    wp_enqueue_style( 'template-shots', get_template_directory_uri() . '/css/template-shots.css' );

    // Template Archive Testimonials
    wp_enqueue_style( 'template-testimonials', get_template_directory_uri() . '/css/template-testimonials.css' );

    // Styling For Footer
    wp_enqueue_style( 'footer', get_template_directory_uri() . '/css/footer.css' );

  }
  
  add_action( 'wp_enqueue_scripts', 'themebs_enqueue_styles');



  // Function To Load JS Scripts
  function themebs_enqueue_scripts() {
    wp_enqueue_script( 'bootstrap', get_template_directory_uri() . '/js/bootstrap.js', array( 'jquery' ) );

    // Removes Useless Margin Top Generated By The WP Head
    remove_action('wp_head', '_admin_bar_bump_cb');

  }
  add_action( 'wp_enqueue_scripts', 'themebs_enqueue_scripts');

  function testimonial_post_type() 
  {
    $args = array(

      'labels' => array(
          'name' => 'Testimonials',
          'singular_name' => 'Testimonial'
      ),
      'hierarchical' =>  false,
      'public' => true,
      'has_archive' => true,
      'menu_icon' => 'dashicons-testimonial',
      'supports' => array('title','editor','thumbnail'),
      
    );

    register_post_type('testimonials', $args);
  }

  add_action('init', 'testimonial_post_type');


  function shot_post_type() 
  {
    $args = array(

      'labels' => array(
          'name' => 'Shots',
          'singular_name' => 'Shot'
      ),
      'hierarchical' =>  false,
      'public' => true,
      'has_archive' => true,
      'menu_icon' => 'dashicons-images-alt2',
      'supports' => array('title','editor','thumbnail'),
      
    );

    register_post_type('shots', $args);
  }

  add_action('init', 'shot_post_type');


  // Custom Image Sizes
  add_image_size( 'small', 180, 300 ); // Size Name, Width, Height
  add_image_size('medium', 450, 450 );
  add_image_size('large', 600, 600);
  add_image_size('x-large', 1024, 1024);

  // Changing excerpt default length
  function new_excerpt_length($length) {
    return 20;
  }
  
  add_filter('excerpt_length', 'new_excerpt_length');


  // Shows Admin Bar If the user is looged in 
  if (is_user_logged_in()) {
    show_admin_bar(true);
  }

  // Customizer File
  require get_template_directory(). '/includes/customizer.php';

  ?>